apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "post-service.fullname" . }}
  labels:
    {{- include "post-service.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "post-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "post-service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: post-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
